### ISSUE TITLE
Typescript constructor example?

### ISSUE THREAD

**Issue by renzor-fist** [ehmicky/modern-errors#12]
Hi there, love the library so far but am struggling with a basic use case in Typescript and am hoping you could provide guidance to help beef up the typescript example section.

I have a HashMismatchError that receives two `props`.

```ts
throw new HashMismatchError(
  `Hash mismatch: expected ${stored.hashValue} but got ${foundHashValue}`,
  {
    props: {
      foundHash: foundHashValue,
      storedHash: stored.hashValue,
    },
  },
)
```

Its defined like this:

```ts
export const HashMismatchError = ModernError.subclass("HashMismatchError", {
  custom: class extends ModernError {
    foundHash: string
    storedHash: string
    constructor(
      message: string,
      options: InstanceOptions<Plugins> | undefined,
    ) {
      super(message, options)
      // @ts-expect-error can't figure out how to type this
      this.foundHash = options?.props?.foundHash
      // @ts-expect-error can't figure out how to type this
      this.storedHash = options?.props?.storedHash
    }
  },
})
```

Could you provide any guidance on how to clean up the constructor function signature and hash variable assignments? It would help me and others understand how to use constructor functions with the library.  Thanks for your awesome lib!

**Comment by ehmicky** [comment]
Hi @renzor-fist,

The main issue is that `props` is a built-in feature with its own semantics. When adding new options, it is advised to make them separate attributes, as opposed to set them inside `props.*`, to avoid conflicting with `props` types. 

In other words, something along the following lines:

```ts
const HashMismatchError = ModernError.subclass("HashMismatchError", {
  custom: class extends ModernError {
    foundHash: string | undefined
    storedHash: string | undefined
    constructor(
      message: string,
      options?: InstanceOptions & { foundHash?: string, storedHash?: string }
    ) {
      super(message, options)
      this.foundHash = options?.foundHash
      this.storedHash = options?.storedHash
    }
  },
})
```

In your case though, you do not need to set `this.foundHash = ...` in the constructor, because `props` are already automatically set on any error instance and correctly typed. I am guessing this might be because you simplified your example for the sake of illustration, is that correct?

**Comment by ehmicky** [comment]
It depends. Are `foundHash` and `storedHash` required? Also, do you want to throw if invalid values are passed to them?

**Comment by ehmicky** [comment]
Good suggestion! I have just improved the following documentation based on our discussion:
  - How to type `props`: https://github.com/ehmicky/modern-errors/blob/main/docs/typescript.md#error-properties-and-methods
  - How to implement custom options: https://github.com/ehmicky/modern-errors#-custom-logic
  - How to type custom options: https://github.com/ehmicky/modern-errors/blob/main/docs/typescript.md#custom-options
  - How to use error classes' and instances' type: https://github.com/ehmicky/modern-errors/blob/main/docs/typescript.md#type-inference

Please let me know what you think!

@all-contributors Could you please add @renzor-fist for question and ideas?
